// Bank Soal Kata Berkait (40 Kolom Lengkap)
const SOAL_DATA = [
  {tema:'Literasi & Buku',g:'g1',soal:[
    {k:'BUKU',b:4,h:'Kumpulan halaman berisi tulisan yang dijilid'},
    {k:'SAMPUL',b:6,h:'Pelindung luar sebuah buku'},
    {k:'HALAMAN',b:7,h:'Satu lembar pada buku'},
    {k:'CERITA',b:6,h:'Isi narasi dalam buku'},
    {k:'TOKOH',b:5,h:'Pelaku atau karakter dalam sebuah cerita'},
    {k:'DIALOG',b:6,h:'Percakapan antar tokoh dalam cerita'},
    {k:'PARAGRAF',b:8,h:'Kumpulan kalimat dalam satu pokok pikiran'},
    {k:'TANDA BACA',b:9,h:'Simbol seperti titik, koma, dan tanda tanya'},
  ]},
  {tema:'Sekolah',g:'g2',soal:[
    {k:'SEKOLAH',b:7,h:'Tempat belajar formal bagi siswa'},
    {k:'KELAS',b:5,h:'Ruangan tempat siswa belajar'},
    {k:'GURU',b:4,h:'Pengajar dan pendidik di sekolah'},
    {k:'MURID',b:5,h:'Peserta didik di sekolah'},
    {k:'UJIAN',b:5,h:'Tes untuk mengukur kemampuan siswa'},
    {k:'NILAI',b:5,h:'Hasil evaluasi prestasi belajar'},
    {k:'IJAZAH',b:6,h:'Surat tanda kelulusan resmi'},
    {k:'PRESTASI',b:8,h:'Pencapaian terbaik yang diraih siswa'},
  ]},
  {tema:'Alam & Lingkungan',g:'g3',soal:[
    {k:'GUNUNG',b:6,h:'Dataran tinggi berbentuk kerucut besar'},
    {k:'HUTAN',b:5,h:'Kawasan luas yang dipenuhi pepohonan'},
    {k:'SUNGAI',b:6,h:'Aliran air tawar yang mengalir di daratan'},
    {k:'SATWA',b:5,h:'Hewan-hewan yang hidup di alam liar'},
    {k:'EKOSISTEM',b:9,h:'Sistem hubungan makhluk hidup dengan lingkungannya'},
    {k:'HABITAT',b:7,h:'Tempat hidup alami suatu makhluk hidup'},
    {k:'LESTARI',b:7,h:'Kondisi alam yang terjaga dan terawat'},
    {k:'KONSERVASI',b:10,h:'Upaya pelestarian dan perlindungan alam'},
  ]},
  {tema:'Masakan & Dapur',g:'g4',soal:[
    {k:'DAPUR',b:5,h:'Ruangan khusus untuk memasak di rumah'},
    {k:'RESEP',b:5,h:'Panduan langkah-langkah membuat masakan'},
    {k:'BUMBU',b:5,h:'Rempah atau bahan penyedap masakan'},
    {k:'REMPAH',b:6,h:'Tanaman aromatik seperti jahe dan kayu manis'},
    {k:'KUNYIT',b:6,h:'Rempah berwarna kuning alami dari akar'},
    {k:'TUMIS',b:5,h:'Teknik memasak cepat dengan sedikit minyak'},
    {k:'SAYUR',b:5,h:'Bahan masak yang berasal dari tumbuhan'},
    {k:'GULAI',b:5,h:'Masakan berkuah santan kental khas Minang'},
  ]},
  {tema:'Sepak Bola',g:'g5',soal:[
    {k:'LAPANGAN',b:8,h:'Area bermain sepak bola berbentuk persegi panjang'},
    {k:'GAWANG',b:6,h:'Target untuk mencetak gol'},
    {k:'WASIT',b:5,h:'Pengatur dan pemimpin jalannya pertandingan'},
    {k:'KARTU',b:5,h:'Hukuman bagi pemain yang melanggar aturan'},
    {k:'OFFSIDE',b:7,h:'Pelanggaran posisi penyerang di depan bek terakhir'},
    {k:'PENALTI',b:7,h:'Tendangan hukuman dari titik 11 meter'},
    {k:'STRIKER',b:7,h:'Pemain penyerang yang bertugas mencetak gol'},
    {k:'TROFI',b:5,h:'Piala atau penghargaan bagi pemenang kompetisi'},
  ]},
  {tema:'Pahlawan & Bangsa',g:'g6',soal:[
    {k:'PAHLAWAN',b:8,h:'Orang yang berjasa besar bagi nusa dan bangsa'},
    {k:'PERJUANGAN',b:10,h:'Upaya keras meraih suatu tujuan mulia'},
    {k:'BANGSA',b:6,h:'Sekumpulan manusia yang memiliki identitas sama'},
    {k:'MERDEKA',b:7,h:'Kondisi bebas dari penjajahan'},
    {k:'PROKLAMASI',b:10,h:'Pengumuman resmi kemerdekaan Indonesia 17 Agustus 1945'},
    {k:'BENDERA',b:7,h:'Simbol negara berbentuk kain dengan warna tertentu'},
    {k:'SUMPAH',b:6,h:'Janji khidmat yang diucapkan dengan sungguh-sungguh'},
    {k:'PEMUDA',b:6,h:'Generasi muda penerus perjuangan bangsa'},
  ]},
  {tema:'Buah-buahan',g:'g7',soal:[
    {k:'MANGGA',b:6,h:'Buah tropis berwarna kuning-hijau berasa manis'},
    {k:'APEL',b:4,h:'Buah bulat berwarna merah atau hijau berasa renyah'},
    {k:'PISANG',b:6,h:'Buah memanjang berwarna kuning kulitnya'},
    {k:'NANAS',b:5,h:'Buah berduri di kulit, manis-asam, mahkota di atas'},
    {k:'PEPAYA',b:6,h:'Buah tropis berdaging oranye dan berbiji hitam'},
    {k:'ANGGUR',b:6,h:'Buah kecil berbentuk bulat tumbuh bergerombol'},
    {k:'RAMBUTAN',b:8,h:'Buah lokal berambut merah di kulitnya'},
    {k:'NANGKA',b:6,h:'Buah besar berduri kecil, berwarna kuning di dalam'},
  ]},
  {tema:'Profesi & Pekerjaan',g:'g8',soal:[
    {k:'DOKTER',b:6,h:'Profesi yang merawat dan menyembuhkan orang sakit'},
    {k:'GURU',b:4,h:'Profesi yang mendidik dan mengajar siswa'},
    {k:'POLISI',b:6,h:'Petugas yang menjaga keamanan dan ketertiban'},
    {k:'PETANI',b:6,h:'Orang yang bekerja mengolah lahan pertanian'},
    {k:'NELAYAN',b:7,h:'Pencari ikan di laut atau sungai'},
    {k:'PILOT',b:5,h:'Pengemudi pesawat terbang'},
    {k:'HAKIM',b:5,h:'Penegak hukum yang memimpin sidang pengadilan'},
    {k:'INSINYUR',b:8,h:'Ahli di bidang teknik dan rekayasa'},
  ]},
  {tema:'Transportasi',g:'g9',soal:[
    {k:'PESAWAT',b:7,h:'Kendaraan terbang bermesin yang mengangkut penumpang'},
    {k:'KAPAL',b:5,h:'Kendaraan besar yang berlayar di lautan'},
    {k:'KERETA',b:6,h:'Kendaraan rel yang membawa banyak penumpang'},
    {k:'MOTOR',b:5,h:'Kendaraan beroda dua bermesin'},
    {k:'BECAK',b:5,h:'Kendaraan roda tiga yang dikayuh atau bermesin kecil'},
    {k:'HELIKOPTER',b:10,h:'Pesawat yang bisa lepas landas secara vertikal'},
    {k:'AMBULANS',b:8,h:'Kendaraan darurat untuk mengangkut pasien'},
    {k:'TREM',b:4,h:'Kendaraan rel yang beroperasi di dalam kota'},
  ]},
  {tema:'Teknologi Digital',g:'g10',soal:[
    {k:'LAPTOP',b:6,h:'Komputer portabel yang bisa dibawa kemana-mana'},
    {k:'PONSEL',b:6,h:'Telepon genggam pintar yang bisa akses internet'},
    {k:'INTERNET',b:8,h:'Jaringan global yang menghubungkan semua komputer'},
    {k:'SERVER',b:6,h:'Komputer pusat yang menyimpan dan melayani data'},
    {k:'APLIKASI',b:8,h:'Program perangkat lunak untuk fungsi tertentu'},
    {k:'KAMERA',b:6,h:'Alat untuk mengambil foto dan video'},
    {k:'SENSOR',b:6,h:'Perangkat pendeteksi perubahan lingkungan'},
    {k:'DIGITAL',b:7,h:'Berbasis data angka biner 0 dan 1'},
  ]},
  {tema:'Hewan Liar',g:'g11',soal:[
    {k:'HARIMAU',b:7,h:'Kucing besar bergaris yang hidup di hutan Asia'},
    {k:'SINGA',b:5,h:'Raja hutan bergigi taring yang hidup di Afrika'},
    {k:'GAJAH',b:5,h:'Hewan darat terbesar dengan belalai panjang'},
    {k:'JERAPAH',b:7,h:'Hewan berleher sangat panjang dari Afrika'},
    {k:'ZEBRA',b:5,h:'Hewan berkuda dengan belang hitam putih'},
    {k:'GORILA',b:6,h:'Kera terbesar yang hidup di hutan Afrika'},
    {k:'BUAYA',b:5,h:'Reptil besar yang hidup di air dan darat'},
    {k:'ELANG',b:5,h:'Burung pemangsa bertubuh besar dan berbulu gagah'},
  ]},
  {tema:'Tumbuhan',g:'g12',soal:[
    {k:'POHON',b:5,h:'Tumbuhan berkayu dengan batang dan dahan besar'},
    {k:'DAUN',b:4,h:'Bagian tumbuhan tempat fotosintesis berlangsung'},
    {k:'AKAR',b:4,h:'Bagian tumbuhan penyerap air di dalam tanah'},
    {k:'BATANG',b:6,h:'Bagian tumbuhan penopang daun dan buah'},
    {k:'BUNGA',b:5,h:'Bagian tumbuhan untuk reproduksi, sering harum'},
    {k:'KLOROFIL',b:8,h:'Zat hijau dalam daun untuk proses fotosintesis'},
    {k:'BIJI',b:4,h:'Cikal bakal tumbuhan baru yang ada dalam buah'},
    {k:'TUNAS',b:5,h:'Bagian tumbuhan muda yang baru tumbuh'},
  ]},
  {tema:'Warna',g:'g13',soal:[
    {k:'MERAH',b:5,h:'Warna api, darah, dan cinta; warna primer'},
    {k:'BIRU',b:4,h:'Warna langit dan lautan; warna primer'},
    {k:'HIJAU',b:5,h:'Warna daun dan alam; campuran biru dan kuning'},
    {k:'KUNING',b:6,h:'Warna matahari dan emas; warna primer'},
    {k:'UNGU',b:5,h:'Campuran warna merah dan biru'},
    {k:'ORANYE',b:6,h:'Campuran merah dan kuning, warna jeruk'},
    {k:'COKELAT',b:7,h:'Warna tanah dan kayu, campuran warna gelap'},
    {k:'PERAK',b:5,h:'Warna logam mulia yang berkilau keabuan'},
  ]},
  {tema:'Musik & Alat Musik',g:'g14',soal:[
    {k:'GITAR',b:5,h:'Alat musik berdawai yang dipetik atau digesek'},
    {k:'PIANO',b:5,h:'Alat musik besar dengan tuts hitam dan putih'},
    {k:'BIOLA',b:5,h:'Alat musik berdawai yang dimainkan dengan busur gesek'},
    {k:'DRUM',b:4,h:'Alat musik perkusi yang dipukul dengan stik'},
    {k:'SERULING',b:8,h:'Alat musik tiup berupa tabung berlubang'},
    {k:'MELODI',b:6,h:'Rangkaian nada yang membentuk lagu yang indah'},
    {k:'HARMONI',b:7,h:'Paduan nada yang selaras dan enak didengar'},
    {k:'RITME',b:5,h:'Pola ketukan dan tempo dalam musik'},
  ]},
  {tema:'Makanan Tradisional',g:'g15',soal:[
    {k:'RENDANG',b:7,h:'Masakan daging berbumbu kaya khas Minangkabau'},
    {k:'SOTO',b:4,h:'Sup berkuah dengan isian daging dan sayuran'},
    {k:'GADO-GADO',b:9,h:'Salad sayuran rebus dengan saus kacang khas Jakarta'},
    {k:'BAKSO',b:5,h:'Bola daging berbumbu yang disajikan dalam kuah kaldu'},
    {k:'SATE',b:4,h:'Daging tusukan yang dibakar dan disajikan dengan bumbu'},
    {k:'OPOR',b:4,h:'Ayam berkuah santan kuning khas masakan Jawa'},
    {k:'KETOPRAK',b:8,h:'Makanan tahu dan lontong saus kacang khas Betawi'},
    {k:'PEMPEK',b:7,h:'Makanan ikan khas Palembang disajikan dengan cuko'},
  ]},
  {tema:'Negara ASEAN',g:'g16',soal:[
    {k:'INDONESIA',b:9,h:'Negara kepulauan terbesar di Asia Tenggara'},
    {k:'MALAYSIA',b:8,h:'Negara bertetangga, ibukota Kuala Lumpur'},
    {k:'SINGAPURA',b:9,h:'Negara kota terkecil di Asia Tenggara'},
    {k:'THAILAND',b:8,h:'Negara ASEAN dengan julukan Negeri Gajah Putih'},
    {k:'VIETNAM',b:7,h:'Negara berbentuk huruf S di Asia Tenggara'},
    {k:'FILIPINA',b:8,h:'Negara kepulauan di utara, ibukota Manila'},
    {k:'KAMBOJA',b:7,h:'Negara yang memiliki candi Angkor Wat'},
    {k:'MYANMAR',b:7,h:'Negara ASEAN yang dulu bernama Burma'},
  ]},
  {tema:'Kota di Indonesia',g:'g17',soal:[
    {k:'JAKARTA',b:7,h:'Ibu kota Indonesia yang terletak di Pulau Jawa'},
    {k:'BANDUNG',b:7,h:'Kota kembang di Jawa Barat, sejuk banyak wisata'},
    {k:'SURABAYA',b:8,h:'Kota pahlawan, kota terbesar kedua di Indonesia'},
    {k:'MEDAN',b:5,h:'Kota terbesar di Pulau Sumatera'},
    {k:'SEMARANG',b:8,h:'Ibukota Jawa Tengah, terkenal dengan Lawang Sewu'},
    {k:'MAKASSAR',b:8,h:'Kota terbesar di Indonesia Timur, Sulawesi Selatan'},
    {k:'PADANG',b:6,h:'Kota di Sumatera Barat terkenal dengan masakan Minang'},
    {k:'DENPASAR',b:8,h:'Ibukota Bali, pusat pariwisata internasional'},
  ]},
  {tema:'Permainan Tradisional',g:'g18',soal:[
    {k:'KASTI',b:5,h:'Permainan lempar tangkap bola beregu'},
    {k:'CONGKLAK',b:8,h:'Permainan papan lubang dengan biji atau kerang'},
    {k:'EGRANG',b:6,h:'Permainan berjalan menggunakan dua tongkat panjang'},
    {k:'BENTENGAN',b:9,h:'Permainan dua tim berebut markas musuh'},
    {k:'GOBAK SODOR',b:11,h:'Permainan lintasan yang dijaga tim lawan'},
    {k:'LAYANG-LAYANG',b:13,h:'Mainan kertas atau plastik yang diterbangkan dengan tali'},
    {k:'YOYO',b:4,h:'Mainan berbentuk dua piringan dengan tali yang dililit'},
    {k:'GASING',b:6,h:'Mainan berputar dengan tali yang dilempar ke tanah'},
  ]},
  {tema:'Ekosistem Laut',g:'g19',soal:[
    {k:'TERUMBU',b:7,h:'Struktur batu karang yang menjadi rumah ikan'},
    {k:'KARANG',b:6,h:'Organisme laut pembentuk terumbu yang keras'},
    {k:'OMBAK',b:5,h:'Gerakan naik turun permukaan air laut'},
    {k:'PANTAI',b:6,h:'Wilayah pertemuan antara darat dan laut'},
    {k:'LUMBA-LUMBA',b:11,h:'Mamalia laut cerdas yang suka melompat'},
    {k:'PENYU',b:5,h:'Reptil laut bercangkang yang bertelur di pantai'},
    {k:'BAKAU',b:5,h:'Hutan pesisir pantai yang akarnya masuk ke air laut'},
    {k:'PLANKTON',b:8,h:'Organisme terkecil di laut, makanan ikan-ikan'},
  ]},
  {tema:'Pakaian Tradisional',g:'g20',soal:[
    {k:'BATIK',b:5,h:'Kain bermotif khas Indonesia, warisan UNESCO'},
    {k:'KEBAYA',b:6,h:'Pakaian tradisional wanita Indonesia'},
    {k:'SARUNG',b:6,h:'Kain panjang yang dililitkan di tubuh'},
    {k:'BLANGKON',b:8,h:'Penutup kepala tradisional pria Jawa'},
    {k:'ULOS',b:4,h:'Kain tenun tradisional khas suku Batak'},
    {k:'SONGKET',b:7,h:'Kain tenun bermotif emas/perak dari Sumatera'},
    {k:'DESTAR',b:6,h:'Penutup kepala khas suku Melayu'},
    {k:'BAJU BODO',b:9,h:'Baju tradisional wanita Bugis Makassar'},
  ]},
  {tema:'Sains & IPA',g:'g21',soal:[
    {k:'ATOM',b:4,h:'Unit terkecil penyusun semua materi'},
    {k:'MOLEKUL',b:7,h:'Gabungan dua atom atau lebih yang terikat'},
    {k:'LISTRIK',b:7,h:'Aliran muatan partikel melalui konduktor'},
    {k:'MAGNET',b:6,h:'Benda yang memiliki gaya tarik terhadap besi'},
    {k:'CAHAYA',b:6,h:'Gelombang elektromagnetik yang bisa dilihat mata'},
    {k:'ENERGI',b:6,h:'Kemampuan untuk melakukan usaha atau kerja'},
    {k:'GRAVITASI',b:9,h:'Gaya tarik bumi terhadap semua benda'},
    {k:'FOTOSINTESIS',b:12,h:'Proses tumbuhan membuat makanan dari sinar matahari'},
  ]},
  {tema:'Matematika',g:'g22',soal:[
    {k:'BILANGAN',b:8,h:'Simbol angka yang digunakan dalam perhitungan'},
    {k:'PECAHAN',b:7,h:'Bilangan yang terdiri dari pembilang dan penyebut'},
    {k:'SEGITIGA',b:8,h:'Bangun datar dengan tiga sisi dan tiga sudut'},
    {k:'LINGKARAN',b:9,h:'Bangun datar yang memiliki jari-jari ke setiap titik'},
    {k:'VOLUME',b:6,h:'Ukuran ruang tiga dimensi dalam sebuah bangun'},
    {k:'SUDUT',b:5,h:'Besaran yang mengukur rotasi antara dua garis'},
    {k:'RASIO',b:5,h:'Perbandingan dua nilai dalam matematika'},
    {k:'PERSAMAAN',b:9,h:'Kalimat matematika yang menyatakan kesamaan dua nilai'},
  ]},
  {tema:'Sastra & Puisi',g:'g23',soal:[
    {k:'PUISI',b:5,h:'Karya sastra bermakna dalam yang tersusun indah'},
    {k:'PANTUN',b:6,h:'Puisi lama bersajak ab-ab berisi sampiran dan isi'},
    {k:'SYAIR',b:5,h:'Puisi lama bersajak aaaa berisi nasihat atau kisah'},
    {k:'PROSA',b:5,h:'Karya sastra berbentuk tulisan bebas tanpa sajak'},
    {k:'METAFORA',b:8,h:'Gaya bahasa perbandingan langsung tanpa kata seperti'},
    {k:'RIMA',b:4,h:'Persamaan bunyi di akhir baris puisi'},
    {k:'DIKSI',b:5,h:'Pilihan kata yang tepat dalam penulisan karya sastra'},
    {k:'MAJAS',b:5,h:'Gaya bahasa untuk memperindah karya sastra'},
  ]},
  {tema:'Bencana Alam',g:'g24',soal:[
    {k:'GEMPA',b:5,h:'Getaran permukaan bumi akibat pergeseran lempeng'},
    {k:'TSUNAMI',b:7,h:'Gelombang laut raksasa akibat gempa bawah laut'},
    {k:'BANJIR',b:6,h:'Luapan air yang menggenangi daratan'},
    {k:'LONGSOR',b:7,h:'Pergerakan massa tanah atau batuan ke bawah lereng'},
    {k:'LETUSAN',b:7,h:'Keluarnya material dari dalam gunung berapi'},
    {k:'BADAI',b:5,h:'Cuaca ekstrem dengan angin kencang dan hujan lebat'},
    {k:'KEKERINGAN',b:10,h:'Kurangnya curah hujan dalam jangka waktu lama'},
    {k:'ABRASI',b:6,h:'Pengikisan pantai oleh gelombang dan arus laut'},
  ]},
  {tema:'Pemerintahan',g:'g25',soal:[
    {k:'PRESIDEN',b:8,h:'Kepala negara dan kepala pemerintahan RI'},
    {k:'MENTERI',b:7,h:'Pembantu presiden yang memimpin kementerian'},
    {k:'GUBERNUR',b:8,h:'Kepala daerah di tingkat provinsi'},
    {k:'BUPATI',b:6,h:'Kepala daerah di tingkat kabupaten'},
    {k:'DEWAN',b:5,h:'Lembaga perwakilan rakyat di tingkat tertentu'},
    {k:'UNDANG-UNDANG',b:13,h:'Peraturan hukum tertinggi yang dibuat oleh negara'},
    {k:'KABINET',b:7,h:'Dewan menteri yang membantu presiden'},
    {k:'ANGGARAN',b:8,h:'Rencana keuangan pemerintah dalam satu tahun'},
  ]},
  {tema:'Keluarga',g:'g26',soal:[
    {k:'AYAH',b:4,h:'Orang tua laki-laki dalam keluarga'},
    {k:'IBU',b:3,h:'Orang tua perempuan dalam keluarga'},
    {k:'KAKAK',b:5,h:'Saudara yang lebih tua dalam keluarga'},
    {k:'ADIK',b:4,h:'Saudara yang lebih muda dalam keluarga'},
    {k:'NENEK',b:5,h:'Ibu dari ayah atau ibu, generasi ketiga ke atas'},
    {k:'KAKEK',b:5,h:'Ayah dari ayah atau ibu, generasi ketiga ke atas'},
    {k:'PAMAN',b:5,h:'Saudara laki-laki dari ayah atau ibu'},
    {k:'SEPUPU',b:6,h:'Anak dari paman atau bibi kita'},
  ]},
  {tema:'Alat Tulis',g:'g27',soal:[
    {k:'PENSIL',b:6,h:'Alat tulis dengan batang grafit bisa dihapus'},
    {k:'PULPEN',b:6,h:'Alat tulis berisi tinta cair dengan ujung bolpoin'},
    {k:'PENGGARIS',b:9,h:'Alat untuk mengukur dan membuat garis lurus'},
    {k:'KERTAS',b:6,h:'Lembaran tipis untuk menulis dan menggambar'},
    {k:'RAUTAN',b:6,h:'Alat untuk meraut ujung pensil agar lancip'},
    {k:'PENGHAPUS',b:9,h:'Alat untuk menghapus tulisan pensil'},
    {k:'SPIDOL',b:6,h:'Alat tulis berujung lunak dengan tinta berwarna'},
    {k:'JANGKA',b:6,h:'Alat gambar untuk membuat lingkaran sempurna'},
  ]},
  {tema:'Jenis Bangunan',g:'g28',soal:[
    {k:'MASJID',b:6,h:'Tempat ibadah umat Islam'},
    {k:'GEREJA',b:6,h:'Tempat ibadah umat Kristiani'},
    {k:'PURA',b:4,h:'Tempat ibadah umat Hindu di Bali'},
    {k:'VIHARA',b:6,h:'Tempat ibadah umat Buddha'},
    {k:'STADION',b:7,h:'Bangunan besar untuk pertandingan olahraga'},
    {k:'MUSEUM',b:6,h:'Gedung penyimpanan benda-benda bersejarah'},
    {k:'TERMINAL',b:8,h:'Tempat pemberhentian kendaraan umum'},
    {k:'BANDARA',b:7,h:'Lapangan dan terminal untuk pesawat terbang'},
  ]},
  {tema:'Tanaman Obat',g:'g29',soal:[
    {k:'JAHE',b:4,h:'Rempah akar berbentuk rimpang, menghangatkan tubuh'},
    {k:'KUNYIT',b:6,h:'Rempah kuning, anti-inflamasi dan antioksidan'},
    {k:'TEMULAWAK',b:9,h:'Tanaman obat untuk menjaga kesehatan hati'},
    {k:'KENCUR',b:6,h:'Rempah kecil akar, dipakai untuk beras kencur'},
    {k:'SIRIH',b:5,h:'Tanaman rambat berdaun hijau, antiseptik alami'},
    {k:'SAMBILOTO',b:9,h:'Tanaman pahit berkhasiat meningkatkan imun tubuh'},
    {k:'LIDAH BUAYA',b:11,h:'Tanaman berdaging tebal berkhasiat untuk kulit'},
    {k:'PEGAGAN',b:7,h:'Tanaman herbal untuk meningkatkan daya ingat'},
  ]},
  {tema:'Tata Surya',g:'g30',soal:[
    {k:'MATAHARI',b:8,h:'Bintang induk di pusat tata surya kita'},
    {k:'BUMI',b:4,h:'Planet tempat kita tinggal, planet ketiga dari matahari'},
    {k:'MARS',b:4,h:'Planet merah, planet keempat dari matahari'},
    {k:'JUPITER',b:7,h:'Planet terbesar di tata surya kita'},
    {k:'SATURNUS',b:8,h:'Planet yang dikelilingi cincin indah dari es dan debu'},
    {k:'KOMET',b:5,h:'Benda langit berekor yang mengorbit matahari'},
    {k:'ASTEROID',b:8,h:'Batu luar angkasa yang mengorbit matahari'},
    {k:'GALAKSI',b:7,h:'Kumpulan miliaran bintang dalam satu sistem'},
  ]},
  {tema:'Bumbu Dapur',g:'g31',soal:[
    {k:'BAWANG MERAH',b:12,h:'Bumbu dasar berwarna merah keunguan'},
    {k:'BAWANG PUTIH',b:12,h:'Bumbu dasar berwarna putih beraroma tajam'},
    {k:'CABAI',b:5,h:'Bumbu pedas berwarna merah atau hijau'},
    {k:'LENGKUAS',b:8,h:'Rempah akar beraroma harum khas masakan Asia'},
    {k:'SERAI',b:5,h:'Batang panjang beraroma wangi khas masakan'},
    {k:'DAUN SALAM',b:10,h:'Daun berbau harum yang digunakan untuk penyedap'},
    {k:'GARAM',b:5,h:'Mineral paling dasar penyedap masakan'},
    {k:'MERICA',b:6,h:'Bumbu bulat kecil memberikan rasa pedas hangat'},
  ]},
  {tema:'Sifat & Karakter Baik',g:'g32',soal:[
    {k:'JUJUR',b:5,h:'Sifat berkata dan bersikap sesuai dengan kenyataan'},
    {k:'RAJIN',b:5,h:'Sifat tekun bekerja dan tidak malas'},
    {k:'SOPAN',b:5,h:'Sifat menghormati dan berlaku baik kepada orang lain'},
    {k:'SABAR',b:5,h:'Kemampuan menahan diri dalam menghadapi cobaan'},
    {k:'BERANI',b:6,h:'Sikap tidak takut menghadapi bahaya demi kebaikan'},
    {k:'ADIL',b:4,h:'Sikap memberikan sesuatu sesuai hak masing-masing'},
    {k:'IKHLAS',b:6,h:'Melakukan sesuatu dengan tulus tanpa mengharap imbalan'},
    {k:'PEDULI',b:6,h:'Rasa perhatian dan empati terhadap orang lain'},
  ]},
  {tema:'Tari Tradisional',g:'g33',soal:[
    {k:'SAMAN',b:5,h:'Tari tradisional dari Aceh yang kompak dan cepat'},
    {k:'KECAK',b:5,h:'Tari sakral dari Bali tanpa iringan gamelan'},
    {k:'JAIPONG',b:7,h:'Tari kreasi khas Jawa Barat yang dinamis'},
    {k:'PENDET',b:6,h:'Tari penyambutan tamu dari Bali'},
    {k:'REOG',b:4,h:'Tari topeng singa dari Ponorogo Jawa Timur'},
    {k:'PIRING',b:6,h:'Tari dari Sumatera Barat yang membawa piring'},
    {k:'ZAPIN',b:5,h:'Tari tradisional Melayu yang ceria dan dinamis'},
    {k:'LEGONG',b:6,h:'Tari Bali yang anggun dimainkan gadis muda'},
  ]},
  {tema:'Alat Musik Tradisional',g:'g34',soal:[
    {k:'GAMELAN',b:7,h:'Seperangkat alat musik pukul khas Jawa dan Bali'},
    {k:'ANGKLUNG',b:8,h:'Alat musik bambu khas Jawa Barat'},
    {k:'SASANDO',b:7,h:'Alat musik petik khas dari Nusa Tenggara Timur'},
    {k:'KECAPI',b:6,h:'Alat musik petik khas Sunda berbentuk perahu'},
    {k:'REBAB',b:5,h:'Alat musik gesek berbentuk mangkuk khas Melayu-Jawa'},
    {k:'KOLINTANG',b:9,h:'Alat musik pukul khas Minahasa Sulawesi Utara'},
    {k:'TIFA',b:4,h:'Alat musik gendang khas Papua berbentuk tabung'},
    {k:'KENDANG',b:7,h:'Gendang utama dalam pertunjukan gamelan Jawa'},
  ]},
  {tema:'Satuan Waktu',g:'g35',soal:[
    {k:'DETIK',b:5,h:'Satuan waktu terkecil yang biasa digunakan'},
    {k:'MENIT',b:5,h:'Satuan waktu yang terdiri dari 60 detik'},
    {k:'JAM',b:3,h:'Satuan waktu yang terdiri dari 60 menit'},
    {k:'HARI',b:4,h:'Satuan waktu yang terdiri dari 24 jam'},
    {k:'MINGGU',b:6,h:'Satuan waktu yang terdiri dari 7 hari'},
    {k:'BULAN',b:5,h:'Satuan waktu sekitar 30 hari dalam kalender'},
    {k:'TAHUN',b:5,h:'Satuan waktu yang terdiri dari 12 bulan atau 365 hari'},
    {k:'ABAD',b:4,h:'Satuan waktu yang terdiri dari 100 tahun'},
  ]},
  {tema:'Cuaca & Iklim',g:'g36',soal:[
    {k:'HUJAN',b:5,h:'Air yang jatuh dari awan ke permukaan bumi'},
    {k:'PETIR',b:5,h:'Kilatan listrik di langit saat cuaca buruk'},
    {k:'MENDUNG',b:7,h:'Kondisi langit tertutup awan gelap'},
    {k:'PELANGI',b:7,h:'Busur warna-warni di langit setelah hujan'},
    {k:'KABUT',b:5,h:'Kumpulan uap air di dekat permukaan tanah'},
    {k:'ANGIN',b:5,h:'Pergerakan massa udara dari satu tempat ke tempat lain'},
    {k:'KEMARAU',b:7,h:'Musim sedikit hujan yang berlangsung lama'},
    {k:'TROPIS',b:7,h:'Iklim daerah sekitar khatulistiwa, panas dan lembab'},
  ]},
  {tema:'Hewan Peliharaan',g:'g37',soal:[
    {k:'KUCING',b:6,h:'Hewan peliharaan berbulu yang gemar tidur dan bermain'},
    {k:'ANJING',b:6,h:'Hewan peliharaan setia, bisa dijadikan penjaga rumah'},
    {k:'KELINCI',b:7,h:'Hewan berbulu telinga panjang yang lucu dan jinak'},
    {k:'HAMSTER',b:7,h:'Hewan kecil berbulu gemuk yang suka berlari di roda'},
    {k:'BURUNG',b:6,h:'Hewan bersayap yang bisa bernyanyi indah'},
    {k:'IKAN HIAS',b:9,h:'Ikan dipelihara di akuarium karena warnanya indah'},
    {k:'KURA-KURA',b:9,h:'Hewan bercangkang keras yang bergerak lambat'},
    {k:'MARMUT',b:6,h:'Hewan berbulu pendek yang ramah dan mudah jinak'},
  ]},
  {tema:'Bunga & Tanaman Hias',g:'g38',soal:[
    {k:'MAWAR',b:5,h:'Bunga simbol cinta dengan duri di batangnya'},
    {k:'MELATI',b:6,h:'Bunga putih harum, bunga nasional Indonesia'},
    {k:'ANGGREK',b:7,h:'Bunga eksotis dengan banyak spesies, mahal harganya'},
    {k:'TULIP',b:5,h:'Bunga berbentuk cangkir dari Belanda, banyak warnanya'},
    {k:'KENANGA',b:7,h:'Bunga kuning harum, bahan baku parfum tradisional'},
    {k:'DAHLIA',b:6,h:'Bunga besar berlapis-lapis, banyak dipakai dekorasi'},
    {k:'LAVENDER',b:8,h:'Tanaman ungu berbau harum, sering dipakai aromaterapi'},
    {k:'KAMBOJA',b:7,h:'Bunga putih kuning harum khas kuil dan pekuburan'},
  ]},
  {tema:'Olahraga Tradisional',g:'g39',soal:[
    {k:'PENCAK SILAT',b:12,h:'Seni bela diri tradisional asli Indonesia'},
    {k:'BAKIAK',b:6,h:'Lomba lari bersandal kayu panjang secara berkelompok'},
    {k:'TARIK TAMBANG',b:13,h:'Lomba dua tim saling menarik tali dengan kekuatan'},
    {k:'PANJAT PINANG',b:13,h:'Lomba memanjat batang pinang yang dilumuri oli'},
    {k:'BALAP KARUNG',b:12,h:'Lomba melompat dalam karung goni khas 17 Agustus'},
    {k:'SEPAK TAKRAW',b:12,h:'Olahraga seperti voli tapi menggunakan kaki dan bola rotan'},
    {k:'HADANG',b:6,h:'Permainan dua tim saling menghalangi di petak tanah'},
    {k:'ENGKLEK',b:7,h:'Permainan melompat dengan satu kaki di kotak gambar'},
  ]},
  {tema:'Kemerdekaan Indonesia',g:'g40',soal:[
    {k:'PROKLAMASI',b:10,h:'Pernyataan resmi kemerdekaan Indonesia 17 Agustus 1945'},
    {k:'PANCASILA',b:9,h:'Dasar negara Indonesia yang terdiri dari lima sila'},
    {k:'BHINNEKA',b:8,h:'Kata pertama moto Indonesia yang berarti berbeda-beda'},
    {k:'MERAH PUTIH',b:11,h:'Bendera kebangsaan Republik Indonesia'},
    {k:'GARUDA',b:6,h:'Lambang negara Indonesia, burung mitologi'},
    {k:'SOEKARNO',b:8,h:'Presiden pertama Republik Indonesia'},
    {k:'MERDEKA',b:7,h:'Kata yang berarti bebas dari penjajahan'},
    {k:'NUSANTARA',b:9,h:'Sebutan lain untuk kepulauan Indonesia'},
  ]},
];
